In [19]:
import requests
import pandas as pd

#access token
token = '579b464db66ec23bdd000001970a9945dc444ac46cdd676f4e569761'

In [23]:
#request to get information from all Mumbai stations
URL = "https://api.data.gov.in/resource/3b01bcb8-0b14-4abf-b6f2-c1bfd384ba69?limit=1000&api-key="+token+"&format=json&filters[city]=Mumbai"
r = requests.get(url = URL)
data = r.json()

In [35]:
def getRecentReading(include_minmax=False):
    recs = data['records']
    stations = {}
    for rec in recs:
        station = rec['station']
        if not (station in stations.keys()):
            row = {'station':station, 'time':rec['last_update']}
            stations[station] = row
        p = rec['pollutant_id']
        p_avg = rec['pollutant_avg']
        p_min = rec['pollutant_min']
        p_max = rec['pollutant_max']
        updates = {p+"_avg":p_avg}
        if include_minmax:
            extra_updates = {p+"_min":p_min, p+"_max":p_max}
        stations[station].update(updates)

    row_ar = []
    for station in stations.keys():
        row_ar.append(stations[station])

    df = pd.DataFrame(row_ar)   
    return df

In [42]:
#use include_minmax_True to include the min and max values in addition to average
getRecentReading(include_minmax=False)

,station,time,PM2.5_avg,PM10_avg,NO2_avg,NH3_avg,SO2_avg,CO_avg,OZONE_avg
0,"Bandra Kurla Complex, Mumbai - IITM",14-03-2023 21:00:00,199,153,157,36,61,38,74
1,"Borivali East, Mumbai - IITM",14-03-2023 21:00:00,NA,NA,79,7,NaN,NaN,NaN
2,"Borivali East, Mumbai - MPCB",14-03-2023 21:00:00,132,119,24,1,8,22,151
3,"Chhatrapati Shivaji Intl. Airport (T2), Mumbai...",14-03-2023 21:00:00,116,177,64,8,11,89,24
4,"Colaba, Mumbai - MPCB",14-03-2023 21:00:00,207,144,NaN,7,22,85,10
5,"Kandivali East, Mumbai - MPCB",14-03-2023 21:00:00,190,164,30,3,51,17,17
6,"Khindipada-Bhandup West, Mumbai - IITM",14-03-2023 21:00:00,165,144,4,NaN,10,70,132
7,"Kurla, Mumbai - MPCB",14-03-2023 21:00:00,54,200,51,4,32,36,116
8,"Malad West, Mumbai - IITM",14-03-2023 21:00:00,NaN,171,8,1,7,68,133
9,"Mazgaon, Mumbai - IITM",14-03-2023 21:00:00,193,171,294,75,90,108,147
10,"Mulund West, Mumbai - MPCB",14-03-2023 21:00:00,201,141,24,9,11,36,NaN
11,"Navy Nagar-Colaba, Mumbai - IITM",14-03-2023 21:00:00,205,132,NaN,NaN,63,NaN,89
12,"Powai, Mumbai - MPCB",14-03-2023 21:00:00,222,140,47,4,14,36,53
13,"Siddharth Nagar-Worli, Mumbai - IITM",14-03-2023 21:00:00,162,114,24,4,NaN,49,153
14,"Sion, Mumbai - MPCB",14-03-2023 21:00:00,235,177,36,5,15,60,17
15,"Vasai West, Mumbai - MPCB",14-03-2023 21:00:00,104,184,11,4,9,55,71
16,"Vile Parle West, Mumbai - MPCB",14-03-2023 21:00:00,NaN,163,65,13,49,66,41
17,"Worli, Mumbai - MPCB",14-03-2023 21:00:00,172,109,44,NaN,4,82,1